<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.Sdk.Testing.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestModule.Backend\TestModule.Backend.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
  </ItemGroup>
</Project>
