<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Properties for all projects in the repository -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <!-- General information -->
    <Description>-</Description>
    <Product>ViciOne Suite SDK</Product>
    <Company>ViciOne open automation gmbh</Company>
    <Year>$([System.DateTime]::Now.Year)</Year>
    <Copyright>Copyright © $(Company) $(Year)</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <SatelliteResourceLanguages>en;de</SatelliteResourceLanguages>

    <!-- Compilation -->
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>

    <!-- Code quality -->
    <TreatWarningsAsErrors Condition="'$(CI)' != '' Or '$(TREAT_WARNINGS_AS_ERRORS)' == 'true'">true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

    <!-- Enable XML documentation for all projects by default as EnforceCodeStyleInBuild relys on it, see https://github.com/dotnet/roslyn/issues/41640 -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!-- NuGet security -->
    <NuGetAuditMode>all</NuGetAuditMode>
  </PropertyGroup>

  <!-- NuGet package properties -->
  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageProjectUrl>https://gitlab.com/vicione-oss/vicione/suite/suite-sdk</PackageProjectUrl>
    <Authors>$(Company)</Authors>
  </PropertyGroup>

  <!-- Configuration for resulting NuGet package -->
  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <!-- Performance optimization for CI pipelines -->
  <PropertyGroup Condition="'$(CI)' != ''">
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    <RunAnalyzers>true</RunAnalyzers>
  </PropertyGroup>

  <!-- Update packages.lock.json with the correct version in local development environment -->
  <PropertyGroup Condition="'$(CI)' == ''">
    <PackageVersion>$([System.IO.File]::ReadAllText('$(MsBuildThisFileDirectory)VERSION').Trim())</PackageVersion>
  </PropertyGroup>

  <PropertyGroup>
    <IsTestProject>$([System.String]::Copy('$(MSBuildProjectName)').EndsWith('Tests'))</IsTestProject>
    <IsInTestFolder>$([System.String]::Copy('$(MSBuildProjectDirectory)').Contains('tests'))</IsInTestFolder>
    <IsInSamplesFolder>$([System.String]::Copy('$(MSBuildProjectDirectory)').Contains('samples'))</IsInSamplesFolder>
  </PropertyGroup>

  <!-- Do not pack and do not publish test projects -->
  <PropertyGroup Condition="'$(IsTestProject)' == 'True'">
    <OutputType>Exe</OutputType>
    <IsPublishable>true</IsPublishable>
    <!-- Microsoft Testing Platform command line experience -->
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <!-- Do not pack test modules or samples -->
  <PropertyGroup Condition="'$(IsInTestFolder)' == 'True' Or '$(IsInSamplesFolder)' == 'True'">
    <IsPackable>false</IsPackable>
    <!-- Microsoft.NET.Sdk.Web enables this warning for non-packable projects, which breaks a solution-wide 'dotnet pack' -->
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsInTestFolder)' == 'True'">
    <Content Include="$(MSBuildThisFileDirectory)xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <!-- Reduce time required to build and also to publish to GitLab pages -->
  <PropertyGroup Condition="'$(IsInSamplesFolder)' == 'True'">
    <CompressionEnabled>false</CompressionEnabled>
  </PropertyGroup>

  <!-- Add Test.SDK/XUnit package references to test projects -->
  <ItemGroup Condition="'$(IsTestProject)' == 'True'">
    <ProjectReference Include="..\..\src\Sdk.Testing\Sdk.Testing.csproj" />

    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Testing.Platform" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
</Project>
