<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <ViciOneCodeAnalysisVersion>1.6.0</ViciOneCodeAnalysisVersion>
    <ViciOneUiMonochromeIconsVersion>4.7.0</ViciOneUiMonochromeIconsVersion>
    <MassTransitVersion>8.5.8</MassTransitVersion>
    <DotNetVersion>10.0.5</DotNetVersion>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="Roslynator.Analyzers" Version="4.15.0" />
    <GlobalPackageReference Include="Roslynator.Formatting.Analyzers" Version="4.15.0" />
    <PackageVersion Include="AspNetCore.SassCompiler" Version="1.97.1" />
    <PackageVersion Include="MassTransit.Abstractions" Version="$(MassTransitVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Authorization" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Authorization" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.UI" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.TypeScript.MSBuild" Version="5.9.3" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageVersion Include="System.IO.Abstractions" Version="22.1.0" />
    <PackageVersion Include="ViciOne.CodeAnalysis.MustCallBase.Attributes" Version="$(ViciOneCodeAnalysisVersion)" />
    <PackageVersion Include="ViciOne.Ui.Blazor.Components" Version="5.6.0" />
    <PackageVersion Include="ViciOne.Ui.Design" Version="2.0.3" />
    <PackageVersion Include="ViciOne.Ui.MonochromeIcons.Assets" Version="$(ViciOneUiMonochromeIconsVersion)" />
    <PackageVersion Include="ViciOne.Ui.MonochromeIcons.Components" Version="$(ViciOneUiMonochromeIconsVersion)" />
    <PackageVersion Include="ViciOne.Ui.Localization" Version="3.2.0" />
    <!--Used for tests only:-->
    <PackageVersion Include="AwesomeAssertions" Version="9.4.0" />
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="bunit" Version="2.6.2" />
    <PackageVersion Include="Extensions.Logging.NSubstitute" Version="1.0.0" />
    <PackageVersion Include="MassTransit.TestFramework" Version="$(MassTransitVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.5.2" />
    <PackageVersion Include="Microsoft.Testing.Platform" Version="2.1.0" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="NSubstitute.Analyzers.CSharp" Version="1.0.17" />
    <PackageVersion Include="System.IO.Abstractions.TestingHelpers" Version="22.1.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
    <PackageVersion Include="xunit.v3.extensibility.core" Version="3.2.2" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>
  <!-- Make ViciOne.CodeAnalysis ... -->
  <ItemGroup Condition="'$(MSBuildProjectFile)' == 'Sdk.csproj'">
    <!-- ... a normal dependency of Sdk to enable our analyzers in consumer projects -->
    <PackageVersion Include="ViciOne.CodeAnalysis.MustCallBase" Version="$(ViciOneCodeAnalysisVersion)" />
  </ItemGroup>
  <ItemGroup Condition="'$(MSBuildProjectFile)' != 'Sdk.csproj'">
    <!-- ... and for other projects we make it a development harness -->
    <GlobalPackageReference Include="ViciOne.CodeAnalysis" Version="$(ViciOneCodeAnalysisVersion)" />
  </ItemGroup>
</Project>
