// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestModule.Backend.DbContext;

#nullable disable

namespace TestModule.Migrations.ReferenceDbContext.Postgres
{
    [DbContext(typeof(ReferenceDbContextPostgres))]
    [Migration("20230127091846_Reference_InitialRefDB")]
    partial class ReferenceInitialRefDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reference")
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestModule.Backend.Contracts.DepartmentEmployees", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("integer");

                    b.Property<string>("dept_no")
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("to_date")
                        .HasColumnType("DATE");

                    b.HasKey("emp_no", "dept_no");

                    b.HasIndex("dept_no");

                    b.ToTable("DepartmentEmployees", "reference");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.DepartmentManager", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("integer");

                    b.Property<string>("dept_no")
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("to_date")
                        .HasColumnType("DATE");

                    b.HasKey("emp_no", "dept_no");

                    b.HasIndex("dept_no");

                    b.ToTable("DepartmentManagers", "reference");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Departments", b =>
                {
                    b.Property<string>("dept_no")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("dept_name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("dept_no");

                    b.ToTable("Departments", "reference");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Employees", b =>
                {
                    b.Property<int>("emp_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("emp_no"));

                    b.Property<DateTime>("birth_date")
                        .HasColumnType("DATE");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<int>("gender")
                        .HasColumnType("integer");

                    b.Property<DateTime>("hire_date")
                        .HasColumnType("DATE");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("emp_no");

                    b.ToTable("Employees", "reference");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Salaries", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("integer");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("DATE");

                    b.Property<int>("salary")
                        .HasColumnType("integer");

                    b.Property<DateTime>("to_date")
                        .HasColumnType("DATE");

                    b.HasKey("emp_no", "from_date");

                    b.ToTable("Salaries", "reference");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Titles", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("to_date")
                        .HasColumnType("DATE");

                    b.HasKey("emp_no", "title", "from_date");

                    b.ToTable("Titles", "reference");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.DepartmentEmployees", b =>
                {
                    b.HasOne("TestModule.Backend.Contracts.Departments", "department")
                        .WithMany("dept_empl")
                        .HasForeignKey("dept_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestModule.Backend.Contracts.Employees", "employee")
                        .WithMany("dept_empl")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.DepartmentManager", b =>
                {
                    b.HasOne("TestModule.Backend.Contracts.Departments", "department")
                        .WithMany("dept_manager")
                        .HasForeignKey("dept_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestModule.Backend.Contracts.Employees", "employee")
                        .WithMany("dept_manager")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Salaries", b =>
                {
                    b.HasOne("TestModule.Backend.Contracts.Employees", "employee")
                        .WithMany("salaries")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Titles", b =>
                {
                    b.HasOne("TestModule.Backend.Contracts.Employees", "employee")
                        .WithMany("titles")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Departments", b =>
                {
                    b.Navigation("dept_empl");

                    b.Navigation("dept_manager");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Employees", b =>
                {
                    b.Navigation("dept_empl");

                    b.Navigation("dept_manager");

                    b.Navigation("salaries");

                    b.Navigation("titles");
                });
#pragma warning restore 612, 618
        }
    }
}
