<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.Sdk.Client.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sdk.Client\Sdk.Client.csproj" />
    <ProjectReference Include="..\TestModule.Client\TestModule.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ViciOne.Ui.Blazor.Components.TestingHelpers" />
  </ItemGroup>

</Project>
