// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestModule.Backend.DbContext;

#nullable disable

namespace TestModule.Migrations.ReferenceDbContext.Sqlite
{
    [DbContext(typeof(ReferenceDbContextSqlite))]
    partial class ReferenceDbContextSqliteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reference")
                .HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("TestModule.Backend.Contracts.DepartmentEmployees", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("INTEGER");

                    b.Property<string>("dept_no")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("to_date")
                        .HasColumnType("DATE");

                    b.HasKey("emp_no", "dept_no");

                    b.HasIndex("dept_no");

                    b.ToTable("DepartmentEmployees", "reference", t =>
                        {
                            t.HasCheckConstraint("deptempl_length_dept_no", "Length(dept_no) < 5 ");
                        });
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.DepartmentManager", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("INTEGER");

                    b.Property<string>("dept_no")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("to_date")
                        .HasColumnType("DATE");

                    b.HasKey("emp_no", "dept_no");

                    b.HasIndex("dept_no");

                    b.ToTable("DepartmentManagers", "reference", t =>
                        {
                            t.HasCheckConstraint("deptmanager_length_dept_no", "Length(dept_no) < 5 ");
                        });
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Departments", b =>
                {
                    b.Property<string>("dept_no")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("dept_name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("dept_no");

                    b.HasIndex("dept_name")
                        .IsUnique();

                    b.ToTable("Departments", "reference", t =>
                        {
                            t.HasCheckConstraint("departments_length_dept_name", "Length(dept_name) < 41 ");

                            t.HasCheckConstraint("departments_length_dept_no", "Length(dept_no) < 5 ");
                        });
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Employees", b =>
                {
                    b.Property<int>("emp_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("birth_date")
                        .HasColumnType("DATE");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<int>("gender")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("hire_date")
                        .HasColumnType("DATE");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("emp_no");

                    b.ToTable("Employees", "reference", t =>
                        {
                            t.HasCheckConstraint("employees_length_first_name", "Length(first_name) < 15 ");

                            t.HasCheckConstraint("employees_length_last_name", "Length(last_name) < 17 ");
                        });
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Salaries", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("DATE");

                    b.Property<int>("salary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("to_date")
                        .HasColumnType("DATE");

                    b.HasKey("emp_no", "from_date");

                    b.ToTable("Salaries", "reference");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Titles", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("to_date")
                        .HasColumnType("DATE");

                    b.HasKey("emp_no", "title", "from_date");

                    b.ToTable("Titles", "reference", t =>
                        {
                            t.HasCheckConstraint("titles_length_title", "Length(title) < 257 ");
                        });
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.DepartmentEmployees", b =>
                {
                    b.HasOne("TestModule.Backend.Contracts.Departments", "department")
                        .WithMany("dept_empl")
                        .HasForeignKey("dept_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestModule.Backend.Contracts.Employees", "employee")
                        .WithMany("dept_empl")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.DepartmentManager", b =>
                {
                    b.HasOne("TestModule.Backend.Contracts.Departments", "department")
                        .WithMany("dept_manager")
                        .HasForeignKey("dept_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestModule.Backend.Contracts.Employees", "employee")
                        .WithMany("dept_manager")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Salaries", b =>
                {
                    b.HasOne("TestModule.Backend.Contracts.Employees", "employee")
                        .WithMany("salaries")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Titles", b =>
                {
                    b.HasOne("TestModule.Backend.Contracts.Employees", "employee")
                        .WithMany("titles")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Departments", b =>
                {
                    b.Navigation("dept_empl");

                    b.Navigation("dept_manager");
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.Employees", b =>
                {
                    b.Navigation("dept_empl");

                    b.Navigation("dept_manager");

                    b.Navigation("salaries");

                    b.Navigation("titles");
                });
#pragma warning restore 612, 618
        }
    }
}
