// <auto-generated/>
// Polyfill required for records / init properties on netstandard2.0

// ReSharper disable once CheckNamespace
namespace System.Runtime.CompilerServices;

internal static class IsExternalInit;
