<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPublishable>true</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sdk.Client.Samples\Sdk.Client.Samples.csproj" />
    <ProjectReference Include="..\Sdk.Client.Samples.Shared\Sdk.Client.Samples.Shared.csproj" />
  </ItemGroup>

</Project>
