// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestModule.Backend.DbContext;

#nullable disable

namespace TestModule.Migrations.TestModuleDbContext.Postgres
{
    [DbContext(typeof(TestModuleDbContextPostgres))]
    partial class TestModuleDbContextPostgresModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("datatypes")
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestModule.Backend.Contracts.SimpleDataTypes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Built")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Users")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SimpleDataTypes", "datatypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Built = new DateTime(2001, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Created = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            MachineDescription = "Presse für Stoßfänger",
                            MachineId = new Guid("ff79fbab-2399-468f-b2ab-1109205dec08"),
                            MachineName = "Presse T1000",
                            Users = 4
                        },
                        new
                        {
                            Id = 2L,
                            Built = new DateTime(2010, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Created = new DateTime(2023, 1, 13, 15, 34, 43, 561, DateTimeKind.Utc).AddTicks(6198),
                            MachineDescription = "Presse für Stoßfänger - T2000",
                            MachineId = new Guid("ca05a1d1-6833-4d76-9231-1ecb60f47fa5"),
                            MachineName = "Presse T2000",
                            Users = 3
                        },
                        new
                        {
                            Id = 3L,
                            Built = new DateTime(2011, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Created = new DateTime(2017, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            MachineDescription = "Presse für Stoßfänger - T5000",
                            MachineId = new Guid("d6aea99b-1f4a-4ed3-ae3f-aef54bb4aad9"),
                            MachineName = "Presse T5000",
                            Users = 1
                        });
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.SimpleEmployees", b =>
                {
                    b.Property<int>("emp_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("emp_no"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Salutaion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("emp_no");

                    b.ToTable("Employees", "datatypes");

                    b.HasData(
                        new
                        {
                            empno = 1,
                            Name = "Hans.Wurst",
                            Salutaion = "Mr"
                        },
                        new
                        {
                            empno = 2,
                            Name = "Karla.Kolumna",
                            Salutaion = "Mrs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
