// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestModule.Backend.DbContext;

#nullable disable

namespace TestModule.Migrations.TestModuleDbContext.Sqlite
{
    [DbContext(typeof(TestModuleDbContextSqlite))]
    partial class TestModuleDbContextSqliteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("datatypes")
                .HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("TestModule.Backend.Contracts.SimpleDataTypes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Built")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Users")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SimpleDataTypes", "datatypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Built = new DateTime(2001, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Created = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            MachineDescription = "Presse für Stoßfänger",
                            MachineId = new Guid("71a29584-3012-484b-8788-03812c638254"),
                            MachineName = "Presse T1000",
                            Users = 4
                        },
                        new
                        {
                            Id = 2L,
                            Built = new DateTime(2010, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Created = new DateTime(2023, 1, 13, 15, 34, 37, 854, DateTimeKind.Utc).AddTicks(8633),
                            MachineDescription = "Presse für Stoßfänger - T2000",
                            MachineId = new Guid("a55aab33-74e0-4191-bf2b-183ddf474c31"),
                            MachineName = "Presse T2000",
                            Users = 3
                        },
                        new
                        {
                            Id = 3L,
                            Built = new DateTime(2011, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Created = new DateTime(2017, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            MachineDescription = "Presse für Stoßfänger - T5000",
                            MachineId = new Guid("0aff3abe-f36b-4a74-a279-2b631940dd73"),
                            MachineName = "Presse T5000",
                            Users = 1
                        });
                });

            modelBuilder.Entity("TestModule.Backend.Contracts.SimpleEmployees", b =>
                {
                    b.Property<int>("emp_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Salutaion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("emp_no");

                    b.ToTable("Employees", "datatypes");

                    b.HasData(
                        new
                        {
                            empno = 1,
                            Name = "Hans.Wurst",
                            Salutaion = "Mr"
                        },
                        new
                        {
                            empno = 2,
                            Name = "Karla.Kolumna",
                            Salutaion = "Mrs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
